---
apiVersion: v1
kind: Pod
metadata:
  name: squash-h2
  labels:
    toto: squash
spec:
  containers:
  - name: squash-h2
    image: squashtest/squash-tm
    resources:
      limits:
        memory: "2Gi"
        cpu: "800m"
    ports:
      - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: squash-h2
spec:
  selector:
    toto: squash
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: NodePort